baseURL = "/"
languageCode = "en-us"
title = "Stanford Education Data Archive"
theme = "base-hugo-theme"
googleAnalytics = ""
paginate = 5

[imaging]
resampleFilter = "box"
quality = 70
anchor = "smart"

[params]
  # google_analytics_id=""
  hideFooter=false
  includeBootstrapJs=true
  containerMaxWidth=1200
  showActiveNav=true
  paginage=5

# main menu

[[menu.main]]
	name = "Home"
	url = "/"
    weight = 1

[[menu.main]]
	name = "Map"
	url = "http://seda-map-prototype.surge.sh/"
    weight = 1

[[menu.main]]
  name = "Explorations"
  url = "/explorations/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "FAQ"
    url = "/help-faq/"
    weight = 4

[[menu.main]]
    name = "Methods"
    url = "/methods/"
    weight = 5

[[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 6

[[menu.main]]
    name = "In the news"
    url = "/news/"
    weight = 7

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"

# Assets needed
# -------------
# * Dark color menu button icon
